global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker-app'
    static_configs:
      - targets: ['app_service:5000']  # Replace app_service with the service name or IP
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
